### ISSUE TITLE
Google data source broken for mutual funds

### ISSUE THREAD

**Issue by duckfloats** [pydata/pandas-datareader#220]
``` python
import pandas_datareader.data as web
import datetime

start = datetime.datetime(2010, 1, 1)
end = datetime.datetime(2013, 1, 27)

f = web.DataReader("F", 'google', start, end)  # this works
f = web.DataReader("VFINX", 'google', start, end)  # this dies
```

output

```
Traceback (most recent call last):
  File "google_bug.py", line 9, in <module>
    f = web.DataReader("VFINX", 'google', start, end)
  File "C:\Anaconda2\lib\site-packages\pandas_datareader\data.py", line 105, in DataReader
    session=session).read()
  File "C:\Anaconda2\lib\site-packages\pandas_datareader\base.py", line 173, in read
    df = self._read_one_data(self.url, params=self._get_params(self.symbols))
  File "C:\Anaconda2\lib\site-packages\pandas_datareader\base.py", line 80, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "C:\Anaconda2\lib\site-packages\pandas_datareader\base.py", line 91, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
  File "C:\Anaconda2\lib\site-packages\pandas_datareader\base.py", line 117, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: http://www.google.com/finance/historical

```

Google supplies "Date, Open, High, Low, Close, Volume" columns for stocks, but only "Date, Close" for mutual funds.

**Comment by femtotrader** [comment]
Hi @duckfloats ,

Thanks for reporting this issue.

I've just merge in master a commit to get a more explicit `RemoteDataError`
see https://github.com/pydata/pandas-datareader/pull/217

so with current master

```python
f = web.DataReader("VFINX", 'google', start, end)
```

now raises

```python
RemoteDataError: Unable to read URL: http://www.google.com/finance/historical?enddate=Jan+27%2C+2013&startdate=Jan+01%2C+2010&q=VFINX&output=csv
```

so if you try with a web browser to go to http://www.google.com/finance/historical?enddate=Jan+27%2C+2013&startdate=Jan+01%2C+2010&q=VFINX&output=csv

you will get a 404 error

So it seems that Google doesn't provide export as CSV file of daily data for mutual funds (they don't provide OHLCV but they also don't provide just close price using this API)

So I don't think that we can do much here (except webscraping webpage which is a pain to do ... and to maintain).

Sorry

**Comment by bashtage** [comment]
This feature is deprecated.
