### ISSUE TITLE
EUROSTAT test is broken

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#228]
```
======================================================================
FAIL: test_get_sts_cobp_a (pandas_datareader.tests.test_eurostat.TestEurostat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/femtotrader/pandas-datareader/pandas_datareader/tests/test_eurostat.py", line 74, in test_get_sts_cobp_a
    tm.assert_series_equal(result, expected)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/pandas/util/testing.py", line 681, in assert_series_equal
    assert_almost_equal(left.values, right.values, check_less_precise)
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2906)
  File "pandas/src/testing.pyx", line 93, in pandas._testing.assert_almost_equal (pandas/src/testing.c:1917)
  File "pandas/src/testing.pyx", line 140, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2724)
AssertionError: expected 200.05000 but got 200.00000, with decimal 5
```

https://travis-ci.org/femtotrader/pandas-datareader/jobs/158256932

**Comment by femtotrader** [comment]
An other test issue

```
KeyError: ('All taxes and levies included', 'Gigajoules (Gross calorific value = GCV)', 'Euro', 'Band D1 : Consumption < 20 GJ', 'Natural gas', 'Denmark', 'Semi-annual')
```

    'Gigajoules (Gross calorific value = GCV)'

should be replaced by

    'Gigajoules (gross calorific value = GCV)'
