### ISSUE TITLE
Pandas DataReader - not able to get quotes when there is a special character in the symbol

### ISSUE THREAD

**Issue by ardnirum** [pydata/pandas-datareader#246]
I have searched thoroughly and I have not seen anyone report this problem.  Here is my code.

``` python
from pandas_datareader import data as web  # data retrieval
web.DataReader("BAJAJ-AUTO.NS", data_source='yahoo', start='2010-02-01', end='2010-02-28')['Adj Close']
```

Here is what I get when I try it out. Same happens when I use the symbol "M&M.NS"

```
  Traceback (most recent call last):
  File "<ipython-input-477-333f8d603959>", line 2, in <module>
  end='2010-02-28')['Adj Close']
  File "D:\Anaconda2\lib\site-packages\pandas_datareader\data.py", line 94,  in DataReader
  session=session).read()

  File "D:\Anaconda2\lib\site-packages\pandas_datareader\yahoo\daily.py",  line 77, in read
  df = super(YahooDailyReader, self).read()

  File "D:\Anaconda2\lib\site-packages\pandas_datareader\base.py", line 173, in read
  df = self._read_one_data(self.url, params=self._get_params(self.symbols))

  File "D:\Anaconda2\lib\site-packages\pandas_datareader\base.py", line 80, in _read_one_data
  out = self._read_url_as_StringIO(url, params=params)

  File "D:\Anaconda2\lib\site-packages\pandas_datareader\base.py", line 91, in _read_url_as_StringIO
  response = self._get_response(url, params=params)

  File "D:\Anaconda2\lib\site-packages\pandas_datareader\base.py", line 117, in _get_response raise RemoteDataError('Unable to read URL: {0}'.format(url))

  RemoteDataError: Unable to read URL: http://ichart.finance.yahoo.com/table.csv
```

Any suggestions?

**Comment by femtotrader** [comment]
Hello @ardnirum 

My first suggestion is to use latest development version
see https://github.com/pydata/pandas-datareader/issues/243

So you will see URL with parameters in `RemoteDataError` like

```
RemoteDataError: Unable to read URL: http://ichart.finance.yahoo.com/table.csv?c=2010&a=1&d=1&ignore=.csv&s=BAJAJ-AUTO.NS&e=28&b=1&g=d&f=2010
```

see https://github.com/pydata/pandas-datareader/issues/216

This kind of "error" looks similar to https://github.com/pydata/pandas-datareader/issues/242

You can try escaping special characters...

Just try simply this URL in a web browser.

But maybe this kind of ticker is not available throw API


Kind regards

**Comment by ardnirum** [comment]
Thanks for looking into the issue @femtotrader 

"My first suggestion is to use latest development version
see #243"
Will do that.

I have tried escape characters.  Not working. The problem as mentioned by you, is on yahoo's side, as the URL is not working on the browser.  But would be good to get better error reporting from pandas.  Will help to focus on the real issue

**Comment by bashtage** [comment]
Yahoo has been deprecated.
