### ISSUE TITLE
Yahoo Options data issue

### ISSUE THREAD

**Issue by delislecl** [pydata/pandas-datareader#259]
Hi,
I have some issues when trying to pull options data with yahoo, here is my code :

```
from pandas_datareader.data import Options
import datetime

getOptions = Options("AAPL", 'yahoo')
data = getOptions.get_all_data()
data.iloc[:,:]
```
Here is the error message i'm getting :

```
Traceback (most recent call last):
  File "P:\Clement\Visual Studio\Python\TestFinanceData\TestFinanceData\TestFinanceData.py", line 5, in <module>
    data = getOptions.get_all_data()
  File "C:\Users\Clement.PANAROMA\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas_datareader\yahoo\options.py", line 593, in get_all_data
    expiry_dates = self.expiry_dates
  File "C:\Users\Clement.PANAROMA\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas_datareader\yahoo\options.py", line 621, in expiry_dates
    expiry_dates, _ = self._get_expiry_dates_and_links()
  File "C:\Users\Clement.PANAROMA\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas_datareader\yahoo\options.py", line 647, in _get_expiry_dates_and_links
    raise RemoteDataError('Data not available') # pragma: no cover
RemoteDataError: Data not available
```
Any idea this could be ? Do you have the same problem ?

Thanks,

**Comment by femtotrader** [comment]
Which version of pandas-datareader are you using ?

Pip install ? or last Github master ?

**Comment by delislecl** [comment]
I have pandas-datareader v0.2.1, it's a pip install yes.
Does my code work on your side ?

Thanks,

**Comment by femtotrader** [comment]
DataReader for Yahoo Options was broken
See https://github.com/pydata/pandas-datareader/issues/212

This PR https://github.com/pydata/pandas-datareader/pull/244
should fix it and will be merged in the next coming days

Please keep updated and use latest Github master version
