### ISSUE TITLE
Tic code when number causes error. Japanese stocks tics in yahoo are numbers. 

### ISSUE THREAD

**Issue by dcgithubaccount** [pydata/pandas-datareader#279]
Please use below code to reproduce the issue

```python
import pandas_datareader.data as web
import datetime
import pandas as pd
import numpy as np
d=datetime.datetime.today()
prevDay = d
minusYear = datetime.timedelta(days=365)
oneYearBeforeDate = prevDay - minusYear
start = datetime.datetime(oneYearBeforeDate.year,
     oneYearBeforeDate.month, oneYearBeforeDate.day)
end = datetime.datetime(prevDay.year, prevDay.month, prevDay.day)
f = web.DataReader(4578, 'yahoo', start, end)
f
```

When i ran below piece of code, it gave me this error. It seems the error is happening because Yahoo Ticker for Japan is Int where as it should be Str.

_It should be tested with str._

```python
a = [x for x in stx['Yahoo Ticker']]
a[0]
f = web.DataReader(a[0],'yahoo',start,end)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/spare/Anaconda/lib/python3.5/site-packages/pandas_datareader/data.py", line 94, in DataReader
    session=session).read()
  File "/spare/Anaconda/lib/python3.5/site-packages/pandas_datareader/yahoo/daily.py", line 77, in read
    df = super(YahooDailyReader, self).read()
  File "/spare/Anaconda/lib/python3.5/site-packages/pandas_datareader/base.py", line 178, in read
    df = self._dl_mult_symbols(self.symbols)
  File "/spare/Anaconda/lib/python3.5/site-packages/pandas_datareader/base.py", line 185, in _dl_mult_symbols
    for sym_group in _in_chunks(symbols, self.chunksize):
  File "/spare/Anaconda/lib/python3.5/site-packages/pandas_datareader/base.py", line 215, in _in_chunks
    return (seq[pos:pos + size] for pos in range(0, len(seq), size))
TypeError: object of type 'numpy.int64' has no len()
```

**Comment by femtotrader** [comment]
On my side

```python
In [11]: import pandas_datareader.data as web
    ...: import datetime
    ...: import pandas as pd
    ...: pd.set_option("max_rows", 10)
    ...: import numpy as np
    ...: d=datetime.datetime.today()
    ...: prevDay = d
    ...: minusYear = datetime.timedelta(days=365)
    ...: oneYearBeforeDate = prevDay - minusYear
    ...: start = datetime.datetime(oneYearBeforeDate.year,
    ...:      oneYearBeforeDate.month, oneYearBeforeDate.day)
    ...: end = datetime.datetime(prevDay.year, prevDay.month, prevDay.day)
    ...: f = web.DataReader(4578, 'yahoo', start, end)
    ...:

In [12]: f
Out[12]:
              Open    High     Low   Close   Volume  Adj Close
Date
2016-02-11  3848.0  3848.0  3848.0  3848.0        0    3769.76
2016-02-12  3778.0  3867.0  3467.0  3774.0  3201700    3697.27
2016-02-15  4000.0  4247.0  3980.0  4200.0  3112300    4114.61
2016-02-16  4051.0  4196.0  4051.0  4142.0  1954000    4057.79
2016-02-17  4138.0  4140.0  3901.0  3938.0  2456100    3857.93
...            ...     ...     ...     ...      ...        ...
2017-02-03  5205.0  5261.0  5165.0  5240.0  1753600    5240.00
2017-02-06  5265.0  5287.0  5242.0  5281.0  1108100    5281.00
2017-02-07  5260.0  5269.0  5212.0  5243.0  1334100    5243.00
2017-02-08  5249.0  5297.0  5228.0  5283.0   951800    5283.00
2017-02-09  5282.0  5313.0  5260.0  5309.0  1829300    5309.00
```

Maybe you need to update pandas-datareader

**Comment by dcgithubaccount** [comment]
Thanks @femtotrader. Update did the trick.
