### ISSUE TITLE
Yahoo unable to retrieve stock with "." characters in name

### ISSUE THREAD

**Issue by twirrim** [pydata/pandas-datareader#282]
The google finance API seems to be completely happy with "BF.B", but Yahoo is barfing on it:

```
>>> ticker
'BF.B'
>>> df = web.DataReader(ticker, "yahoo", start, end)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pgraydon/Envs/finance/lib/python3.6/site-packages/pandas_datareader/data.py", line 116, in DataReader
    session=session).read()
  File "/Users/pgraydon/Envs/finance/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py", line 76, in read
    df = super(YahooDailyReader, self).read()
  File "/Users/pgraydon/Envs/finance/lib/python3.6/site-packages/pandas_datareader/base.py", line 155, in read
    df = self._read_one_data(self.url, params=self._get_params(self.symbols))
  File "/Users/pgraydon/Envs/finance/lib/python3.6/site-packages/pandas_datareader/base.py", line 74, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "/Users/pgraydon/Envs/finance/lib/python3.6/site-packages/pandas_datareader/base.py", line 85, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
  File "/Users/pgraydon/Envs/finance/lib/python3.6/site-packages/pandas_datareader/base.py", line 120, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: http://ichart.finance.yahoo.com/table.csv?s=BF.B&a=0&b=1&c=2000&d=11&e=31&f=2016&g=d&ignore=.csv
>>> df = web.DataReader(ticker, "google", start, end)
>>>
```

**Comment by femtotrader** [comment]
See http://finance.yahoo.com/quote/BF-B

```python
In [1]: import pandas_datareader as web
i
In [2]: import pandas as pd

In [3]: pd.set_option("max_rows", 10)

In [4]: df = web.DataReader("BF-B", "yahoo")

In [5]: df
Out[5]:
                 Open       High        Low      Close   Volume  Adj Close
Date
2010-01-04  53.569994  54.229998  53.539993  53.800003   935400  15.828047
2010-01-05  53.639997  53.869995  52.620003  53.239992  1206200  15.663290
2010-01-06  53.329994  54.079994  53.239992  53.980007  1198400  15.881004
2010-01-07  54.079994  54.079994  53.200006  53.449997   642200  15.725074
2010-01-08  53.470007  53.479998  52.849995  53.440006   649200  15.722135
...               ...        ...        ...        ...      ...        ...
2017-02-06  45.599998  45.830002  45.119999  45.450001   540600  45.450001
2017-02-07  45.439999  45.830002  45.439999  45.779999   828300  45.779999
2017-02-08  45.639999  46.279999  45.630001  46.189999   645300  46.189999
2017-02-09  46.090000  46.700001  46.049999  46.660000   549200  46.660000
2017-02-10  46.509998  47.139999  46.450001  46.959999   737700  46.959999

[1790 rows x 6 columns]
```

**Comment by twirrim** [comment]
If I understand it correctly, the official stock ticker appears to be "BF.B", while Yahoo is translating it as "BF-B"?  (see also https://www.nyse.com/quote/XNYS:BF.B )

To gain consistency, and arguably correctness, is it worth trying to automatically translate the "." to "-" automatically for the eventual call to Yahoo?

**Comment by femtotrader** [comment]
Do you know some others tickers with a "." character in name?

**Comment by itzybitzy** [comment]
The best-known are probably BRK.A and BRK.B. Looking down a list, some other examples are BIO.B, CBS.A, GEF.B.

**Comment by bashtage** [comment]
dot symbols for common for non-us symbols, e.g., VOD.L

**Comment by itzybitzy** [comment]
On Yahoo, VOD.L is a legitimate ticker (Vodafone trading on LSE) but BRK.A is not -- Yahoo translates the .A (meaning class A shares) to a -A, so the correct ticker is BRK-A.

**Comment by twirrim** [comment]
Hmm.  Wonder if there are any stock symbols including ".A" or ".B" that aren't class A or class B?

**Comment by jainraje** [comment]
Here are several stocks I had to manually add a '-' to get working with Yahoo: BF-B, BRK-B, FCE-A, JW-A, LGF-A, LGF-B, PBR-A, RDS-A, RDS-B.

**Comment by ruhtroh** [comment]
Instead of manually trying to fix stocks that contain a '.', why not just do a `str.replace('.', '-')`?

**Comment by twirrim** [comment]
That won't work.  As noted: VOD.L is a legitimate ticker for Yahoo.  If a str.replace was done it would catch those cases and break them.

**Comment by ruhtroh** [comment]
I tried out this case: 
```
for ticker in tickers:
        if not os.path.exists('stock_dfs/{}.csv'.format(ticker)):
            print('Creating {}')
            df = web.DataReader(ticker.replace('.', '-'), 'yahoo', start, end)
            df.to_csv('stock_dfs/{}.csv'.format(ticker))
        else:
            print('Already have {}'.format(ticker))
```

Each time this loop encountered a stock symbol with '.' it was still able to execute the remaining actions, and still converted something like 'BRK.B' to 'BRK-B', then returned the .csv file "BRK.B.csv"

I may be out of the scope of the question, but this fixed my error with the dotted stock tickers.

**Comment by jainraje** [comment]
This is a useful code snippet. For my case, the symbols (giving me issue) are provided without the '.', so converting '.' to '-' will not work. For example, the symbols requiring conversion are BFB, BRKB, FCEA, JWA, LGFA, LGFB, PBRA, RDSA, RDSB. I can write a small block of code to convert those symbols. thanks for comments.

**Comment by aking1012** [comment]
Also, all canadian exchange stocks are .to AW-UN.TO should resolve properly if there's a test case to be written.

**Comment by aschilling** [comment]
Hi everybody,

I experience various problems fetching data for german stocks such as ADS.DE. Is this related to your problems? I get the error message 
_Unable to read URL: https://query1.finance.yahoo.com/v7/finance/download/..._ 

Curiously, if I try various times after the error message, the error disapears, is this an issue with the requests package?

If this is not related to your problems please let me know, so I can open a new issue.

**Comment by bashtage** [comment]
Yahoo has been deprecated.
