### ISSUE TITLE
import error with pandas=20.1

### ISSUE THREAD

**Issue by MMCMA** [pydata/pandas-datareader#323]
After upgrading pandas to pandas=0.20.1, pandas_datareader raises the following import error

```
import pandas_datareader
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-89e32976a845>", line 1, in <module>
    import pandas_datareader
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\pandas_datareader\__init__.py", line 3, in <module>
    from .data import (get_components_yahoo, get_data_famafrench, get_data_google, get_data_yahoo, get_data_enigma,  # noqa
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\pandas_datareader\data.py", line 7, in <module>
    from pandas_datareader.google.daily import GoogleDailyReader
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\pandas_datareader\google\daily.py", line 1, in <module>
    from pandas_datareader.base import _DailyBaseReader
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\pandas_datareader\base.py", line 13, in <module>
    from pandas_datareader._utils import (RemoteDataError, SymbolWarning,
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\pandas_datareader\_utils.py", line 5, in <module>
    from pandas.core.common import PandasError
ImportError: cannot import name 'PandasError'
```

**Comment by MMCMA** [comment]
#304 already solved, just saw it
