### ISSUE TITLE
conda env with python 3.6.1 fails import of data and wb for v0.2.1

### ISSUE THREAD

**Issue by behudson** [pydata/pandas-datareader#341]
$ python
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pandas_datareader import data, wb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<USER>/miniconda2/envs/jp/lib/python3.6/site-packages/pandas_datareader/data.py", line 7, in <module>
    from pandas_datareader.google.daily import GoogleDailyReader
  File "/home/<USER>/miniconda2/envs/jp/lib/python3.6/site-packages/pandas_datareader/google/daily.py", line 1, in <module>
    from pandas_datareader.base import _DailyBaseReader
  File "/home/<USER>/miniconda2/envs/jp/lib/python3.6/site-packages/pandas_datareader/base.py", line 11, in <module>
    from pandas.core.common import PandasError, is_number
ImportError: cannot import name 'PandasError'
>>>

**Comment by WBare** [comment]
Hi Brad,

Are you using pandas 0.20?  If so, it looks like this is covered over here:
https://github.com/pydata/pandas-datareader/pull/304

**Comment by behudson** [comment]
Yes. It looks like this was fixed in #324
<https://github.com/pydata/pandas-datareader/issues/324>, but is not
available from Continuum Analytics (e.g. "conda install
pandas-datareader"), which may be why it still occurs in my environment.

**Comment by WBare** [comment]
Go to the conda website and search for pandas-datareader.  The default is not up to date.  Try this:
conda install -c conda-forge pandas-datareader=0.4.0

**Comment by behudson** [comment]
Thanks for the tip to use conda-forge for this. Version 0.4.0 seems to work for Google, but not Yahoo.

>>> pdr.data.DataReader('AAPL', 'google').head()
             Open   High    Low  Close     Volume
Date                                             
2010-01-04  30.49  30.64  30.34  30.57  123432050
2010-01-05  30.66  30.80  30.46  30.63  150476004
2010-01-06  30.63  30.75  30.11  30.14  138039594
2010-01-07  30.25  30.29  29.86  30.08  119282324
2010-01-08  30.04  30.29  29.87  30.28  111969081
>>> pdr.data.DataReader('AAPL', 'yahoo').head()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<USER>/miniconda2/envs/jp/lib/python3.6/site-packages/pandas_datareader/data.py", line 117, in DataReader
    session=session).read()
  File "/home/<USER>/miniconda2/envs/jp/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py", line 77, in read
    df = super(YahooDailyReader, self).read()
  File "/home/<USER>/miniconda2/envs/jp/lib/python3.6/site-packages/pandas_datareader/base.py", line 157, in read
    params=self._get_params(self.symbols))
  File "/home/<USER>/miniconda2/envs/jp/lib/python3.6/site-packages/pandas_datareader/base.py", line 74, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "/home/<USER>/miniconda2/envs/jp/lib/python3.6/site-packages/pandas_datareader/base.py", line 85, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
  File "/home/<USER>/miniconda2/envs/jp/lib/python3.6/site-packages/pandas_datareader/base.py", line 120, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: http://ichart.finance.yahoo.com/table.csv?s=AAPL&a=0&b=1&c=2010&d=4&e=26&f=2017&g=d&ignore=.csv
>>>

**Comment by WBare** [comment]
yes, that is a different issue.  Yahoo finance just recently shut town the service they were running.  There is a way to adapt pandas-datareader to the new method, but I don't know if anyone is taking up that challenge.  Check out the issues posted on datareader and you will see if posted a bunch of times.

**Comment by jreback** [comment]
closing as user issue.
