### ISSUE TITLE
Issue with the dollar sign ('$') character and get_data_yahoo()

### ISSUE THREAD

**Issue by andj3w** [pydata/pandas-datareader#386]
Code for script `setup.py` that creates the error:
```python
import pandas_datareader.data as web

nasdaq_data = web.get_nasdaq_symbols()
symbols = nasdaq_data.index.values
web.get_data_yahoo('ABR-PA') #works
for x in symbols:
    print 'Getting data for: %s' % x
    web.get_data_yahoo(x) #throws RemoteDataError
```

Terminal output: 
```
Getting data for: A
Getting data for: AA
Getting data for: AAAP
Getting data for: AABA
...
Getting data for: ABR$A
Traceback (most recent call last):
  File "../setup.py", line 23, in <module>
    web.get_data_yahoo(x)
  File "/usr/local/lib/python2.7/dist-packages/pandas_datareader/data.py", line 40, in get_data_yahoo
    return YahooDailyReader(*args, **kwargs).read()
  File "/usr/local/lib/python2.7/dist-packages/pandas_datareader/yahoo/daily.py", line 115, in read
    df = super(YahooDailyReader, self).read()
  File "/usr/local/lib/python2.7/dist-packages/pandas_datareader/base.py", line 181, in read
    params=self._get_params(self.symbols))
  File "/usr/local/lib/python2.7/dist-packages/pandas_datareader/base.py", line 79, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "/usr/local/lib/python2.7/dist-packages/pandas_datareader/base.py", line 90, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
  File "/usr/local/lib/python2.7/dist-packages/pandas_datareader/base.py", line 139, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: https://query1.finance.yahoo.com/v7/finance/download/ABR$A?crumb=nWOYHc6s101&interval=1d&period2=1504411199&events=history&period1=1262322000
```

There is incomplete compatibility between the method `get_nasdaq_symbols()` and the method `get_data_yahoo()`. NASDAQ represents option chains with a '^' on their website and with a '$' or '-' within the data returned by `get_nasdaq_symbols()`. Yahoo uses '-P' to represent the same character. 

The dollar sign is not a valid character in any symbol name. The `get_data_yahoo()` method should replace '$' with '-P' in any symbol name or list passed to it.

**Comment by bashtage** [comment]
Yahoo has been deprecated.
