### ISSUE TITLE
'utf-8' Encoding + 'unable to read URL' errors: when downloading financial data from yahoo and google

### ISSUE THREAD

**Issue by inesazaiez** [pydata/pandas-datareader#428]
Hi all, I am using Python 3 on Mac OS X. I would like to download S&P 500 data using yahoo finance (somehow it is still working but then throwing an error) and using google finance.

The code I am using 
`from datetime import *`
`import bs4 as bs`
`import datetime as dt`
`import os`
`import pandas as pd`
`import pandas_datareader.data as data`
`import pickle`
`import requests`

`SnP = pd.DataFrame()`
`start = dt.datetime(2000, 1, 1)`
`end = datetime.now()`
`for ticker in tickers:`
          `---stock = data.DataReader(ticker, data_source, start, end)`
          ` ---SnP[ticker] = stock['Open']`

Given that: 
- tickers is a list of stock tickers, i.e `tickers = ['MMM', 'ABT', 'ABBV', 'ACN',...,'ZION', 'ZTS']` 
- data_source is either `'yahoo'` or `'google'`

1. Using yahoo API, i.e `data_source = 'yahoo'` the code works for the first few tickers then throws me the following error:
`Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/data.py", line 121, in DataReader
    session=session).read()
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py", line 115, in read
    df = super(YahooDailyReader, self).read()
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/base.py", line 181, in read
    params=self._get_params(self.symbols))
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/base.py", line 79, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/base.py", line 90, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/base.py", line 139, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: https://query1.finance.yahoo.com/v7/finance/download/AYI?period1=946681200&period2=1512946799&interval=1d&events=history&crumb=hnxNmU%5Cu002FEQJS
`
However, if only used with one ticker, the same code works perfectly fine, i.e
`import pandas_datareader.data as data`
`start = datetime(2016, 12, 31)`
`end = datetime.now()`
`AAPL = data.DataReader('APPL', 'yahoo', start, end)`

2. When I use google API, i.e `data_source = 'google'`, I am getting this error:
`Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/data.py", line 137, in DataReader
    session=session).read()
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/base.py", line 181, in read
    params=self._get_params(self.symbols))
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/base.py", line 79, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/base.py", line 98, in _read_url_as_StringIO
    out.write(bytes_to_str(text))
  File "/usr/local/lib/python3.6/site-packages/pandas/compat/__init__.py", line 74, in bytes_to_str
    return b.decode(encoding or 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 18101: invalid start byte`

Would you please help me out with error 1 and 2? I already googled for those errors, and saw related topics on github and ..., withtout success in making the code work.

ps: I am new to Python. Using it since a week. 

Thank you :)

**Comment by nzd31155** [comment]
check this thread - https://github.com/pydata/pandas-datareader/issues/424

**Comment by inesazaiez** [comment]
Thanks :) Yes, I already went through it, helpful for getting the result but not for understanding why I am getting these errors.

**Comment by bashtage** [comment]
Yahoo has been deprecated.
