### ISSUE TITLE
Python data reader having issues fetching data from Yahoo Finance [duplicate]

### ISSUE THREAD

**Issue by tenichols** [pydata/pandas-datareader#434]
I am scraping stock data from Yahoo Finance using pythons data reader. The code below works I would say 75% of the time but throws an error the other 25%. Below is the code and below will be error it is displaying. I have searched this issue a few times, but have not found a solution. Hopefully somebody can help me out. Thank you!

Below is the code

```
import datetime as dt
import pandas as pd
import pandas_datareader.data as web

start = datetime.datetime(2017, 10, 9)
end = datetime.datetime(2017, 10, 11)
data = web.DataReader('AAPL', 'yahoo', start, end)
```

Below is the error

` Traceback (most recent call last):
  File "<pyshell#27>", line 1, in <module>
    data = web.DataReader('AAPL', 'yahoo', start, end)
  File "C:\Program Files\Python36\lib\site-packages\pandas_datareader\data.py", line 121, in DataReader
    session=session).read()
  File "C:\Program Files\Python36\lib\site-packages\pandas_datareader\yahoo\daily.py", line 115, in read
    df = super(YahooDailyReader, self).read()
  File "C:\Program Files\Python36\lib\site-packages\pandas_datareader\base.py", line 181, in read
    params=self._get_params(self.symbols))
  File "C:\Program Files\Python36\lib\site-packages\pandas_datareader\base.py", line 79, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "C:\Program Files\Python36\lib\site-packages\pandas_datareader\base.py", line 90, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
  File "C:\Program Files\Python36\lib\site-packages\pandas_datareader\base.py", line 139, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: https://query1.finance.yahoo.com/v7/finance/download/AAPL?period1=1507525200&period2=1507784399&interval=1d&events=history&crumb=1kbXC%5Cu002Fro3k1`

**Comment by bashtage** [comment]
Yahoo has been deprecated.
