### ISSUE TITLE
http://pandas.pydata.org/pandas-docs/version/0.16.1/pandas.pdf - 25.2 Yahoo! Finance Options

### ISSUE THREAD

**Issue by toasteez** [pydata/pandas-datareader#46]
Is this expected?

>>> from pandas.io.data import Options
>>> aapl = Options('aapl', 'yahoo')
>>> data = aapl.get_all_data()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\pandas\io\data.py", line 1115, in get_all_data
    expiry_dates = self.expiry_dates
  File "C:\Anaconda\lib\site-packages\pandas\io\data.py", line 1146, in expiry_dates
    expiry_dates, _ = self._get_expiry_dates_and_links()
  File "C:\Anaconda\lib\site-packages\pandas\io\data.py", line 1161, in _get_expiry_dates_and_links
    root = self._parse_url(url)
  File "C:\Anaconda\lib\site-packages\pandas\io\data.py", line 1193, in _parse_url
    "{0!r}".format(url))
RemoteDataError: Unable to parse URL 'http://finance.yahoo.com/q/op?s=AAPL'
>>>

**Comment by dstephens99** [comment]
Looks like it got rebuilt - the PDF is fine now.  Thanks for bringing it up.
