### ISSUE TITLE
fred.py - cannot import name is_list_like: ImportError

### ISSUE THREAD

**Issue by mindtd** [pydata/pandas-datareader#534]
While using zappa-deploy to AWS lambda, got this error message.

cannot import name is_list_like: ImportError
Traceback (most recent call last):
File "/var/task/handler.py", line 509, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 237, in lambda_handler
handler = cls()
File "/var/task/handler.py", line 129, in __init__
self.app_module = importlib.import_module(self.settings.APP_MODULE)
File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
File "/var/task/portfolio_game.py", line 10, in <module>
from pandas_datareader import data
File "c:\users\user\appdata\local\temp\pip-build-ovycb5\pandas-datareader\pandas_datareader\__init__.py", line 2, in <module>
File "c:\users\user\appdata\local\temp\pip-build-ovycb5\pandas-datareader\pandas_datareader\data.py", line 14, in <module>
File "c:\users\user\appdata\local\temp\pip-build-ovycb5\pandas-datareader\pandas_datareader\fred.py", line 1, in <module>
ImportError: cannot import name is_list_like

Workaround - remove fred.py altogether, and comment out
_init_,py - from .data import(..., get_data_fred ...)
data.py - from pandas_datareader.fred import FredReader, def get_data_fred(*args, **kwargs), elif data_source == "fred"

**Comment by addisonlynch** [comment]
This has been repaired in #520. It's best to download the development version (the current master of this repo) to avoid this problem. The repair will be integrated into the next release (0.7.0) as well

**Comment by yurivict** [comment]
Please make a release with the fix.
