### ISSUE TITLE
OECD data -- unknonw date format

### ISSUE THREAD

**Issue by jvlcekatcz** [pydata/pandas-datareader#585]
Guy,
Thank you for nice pandas-datareader. Using Win-Python, Spyder I following error for the OECD case. Thank you for your help.

COMMAND: df = web.DataReader('MEI_FIN', 'oecd', end=datetime.datetime(2012, 1, 1))

Traceback (most recent call last):

  File "<ipython-input-375-be1648dafeb2>", line 1, in <module>
    df = web.DataReader('MEI_FIN', 'oecd', end=datetime.datetime(2012, 1, 1))

  File "C:\fs\WPy-3661\python-3.6.6.amd64\lib\site-packages\pandas_datareader\data.py", line 364, in DataReader
    session=session).read()

  File "C:\fs\WPy-3661\python-3.6.6.amd64\lib\site-packages\pandas_datareader\base.py", line 77, in read
    return self._read_one_data(self.url, self.params)

  File "C:\fs\WPy-3661\python-3.6.6.amd64\lib\site-packages\pandas_datareader\base.py", line 89, in _read_one_data
    return self._read_lines(out)

  File "C:\fs\WPy-3661\python-3.6.6.amd64\lib\site-packages\pandas_datareader\oecd.py", line 26, in _read_lines
    df = read_jsdmx(out)

  File "C:\fs\WPy-3661\python-3.6.6.amd64\lib\site-packages\pandas_datareader\io\jsdmx.py", line 44, in read_jsdmx
    index = _parse_dimensions(structure['dimensions']['observation'])

  File "C:\fs\WPy-3661\python-3.6.6.amd64\lib\site-packages\pandas_datareader\io\jsdmx.py", line 97, in _parse_dimensions
    values = pd.DatetimeIndex(values)

  File "C:\fs\WPy-3661\python-3.6.6.amd64\lib\site-packages\pandas\core\indexes\datetimes.py", line 399, in __new__
    yearfirst=yearfirst)

  File "C:\fs\WPy-3661\python-3.6.6.amd64\lib\site-packages\pandas\core\tools\datetimes.py", line 467, in to_datetime
    result = _convert_listlike(arg, box, format)

  File "C:\fs\WPy-3661\python-3.6.6.amd64\lib\site-packages\pandas\core\tools\datetimes.py", line 380, in _convert_listlike
    raise e

  File "C:\fs\WPy-3661\python-3.6.6.amd64\lib\site-packages\pandas\core\tools\datetimes.py", line 368, in _convert_listlike
    require_iso8601=require_iso8601

  File "pandas\_libs\tslib.pyx", line 492, in pandas._libs.tslib.array_to_datetime

  File "pandas\_libs\tslib.pyx", line 739, in pandas._libs.tslib.array_to_datetime

  File "pandas\_libs\tslib.pyx", line 733, in pandas._libs.tslib.array_to_datetime

  File "pandas\_libs\tslibs\parsing.pyx", line 99, in pandas._libs.tslibs.parsing.parse_datetime_string

  File "C:\fs\WPy-3661\python-3.6.6.amd64\lib\site-packages\dateutil\parser\_parser.py", line 1356, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)

  File "C:\fs\WPy-3661\python-3.6.6.amd64\lib\site-packages\dateutil\parser\_parser.py", line 648, in parse
    raise ValueError("Unknown string format:", timestr)

ValueError: ('Unknown string format:', 'Q1-1958')

**Comment by jeremywhelchel** [comment]
I hit this as well. It appears to be because the OECD dataset is returning some quarter datetimes that look like 'Q4-2018'. Pandas doesn't like that format (at least Pandas v22.0, which I'm using).
If you convert them to '2018Q4', right before the pd.DatetimeIndex() call, it should work.

I'll put together a PR to fix this.

**Comment by jvlcekatcz** [comment]
Jeremy,

Thank you. Jan

**Comment by jeremywhelchel** [comment]
While fixing the quarter date format I discovered there might be a more serious issue with the JSDMX library. It looks like the datasets being returned by OECD are not in a sorted order, but the library seems to assume they are. Will need to do a little work to figure out what's going on there and align the indices properly.
