### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Yachter** [pydata/pandas-datareader#614]
```
>>> data_reader.get_dividends('AEOXF', 2018,  2019)

Traceback (most recent call last):
  Debug Probe, prompt 114, line 1
    import datetime
  File "C:\TEST\data_reader.py", line 14, in get_dividends
    return web.DataReader (sym, 'yahoo-dividends', start = start_year, end = end_year)
  File "C:\Program Files\Python37\Lib\site-packages\pandas_datareader\data.py", line 407, in DataReader
    session=session, interval='d').read()
  File "C:\Program Files\Python37\Lib\site-packages\pandas_datareader\yahoo\actions.py", line 51, in read
    data = super(YahooDivReader, self).read()
  File "C:\Program Files\Python37\Lib\site-packages\pandas_datareader\yahoo\actions.py", line 13, in read
    data = super(YahooActionReader, self).read()
  File "C:\Program Files\Python37\Lib\site-packages\pandas_datareader\base.py", line 210, in read
    params=self._get_params(self.symbols))
  File "C:\Program Files\Python37\Lib\site-packages\pandas_datareader\yahoo\daily.py", line 142, in _read_one_data
    to_datetime(prices['Date'], unit='s').dt.date)
  File "C:\Program Files\Python37\Lib\site-packages\pandas\core\frame.py", line 2917, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Program Files\Python37\Lib\site-packages\pandas\core\indexes\base.py", line 2604, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "C:\Program Files\Python37\Lib\site-packages\pandas\_libs\index.cp37-win_amd64.pyd", line 108, in pandas._libs.index.IndexEngine.get_loc
    HSHËÿR0HÆéeÿÿÿÌÌÌÌÌÌÌÌÌÌÌÌÌ
ÉJ\000\000H\$Hl$ VHì H5j¤\000HÚéH
öuH¹\000\000\000ÿÝ
  File "C:\Program Files\Python37\Lib\site-packages\pandas\_libs\index.cp37-win_amd64.pyd", line 132, in pandas._libs.index.IndexEngine.get_loc
    HCHËÿP0¸ÿÿÿÿH\$0HÄ _ÃH
Éu
  File "C:\Program Files\Python37\Lib\site-packages\pandas\_libs\hashtable.cp37-win_amd64.pyd", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
    7\000H
  File "C:\Program Files\Python37\Lib\site-packages\pandas\_libs\hashtable.cp37-win_amd64.pyd", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
    ÿ1\000L4\000MIH
builtins.KeyError: 'Date'
```

**Comment by okomarov** [comment]
Seems like Yahoo is broken again. The return and empty cache:|

In `pandas_datareader/yahoo/daily.py` under `YahooDailyReader._read_one_data`, the line:
```
j['context']['dispatcher']['stores']['HistoricalPriceStore']
```
returns 
```
{'prices': [], 'isPending': False, 'firstTradeDate': 863683200, 'id': '1d15492528001549339199', 'timeZone': {'gmtOffset': -18000}, 'eventsData': []}
```

We should implement proper breadcrumb fetching like in: https://github.com/AndrewRPorter/yahoo-historical/blob/master/yahoo_historical/fetch.py

**Comment by gliptak** [comment]
Works with current stable. Please consider closing.

```
>>> import pandas_datareader as web
>>> web.__version__
'0.7.4'
>>> web.DataReader('AEOXF', 'yahoo-dividends', 2018,  2019)
/opt/conda/lib/python3.7/site-packages/pandas_datareader/yahoo/actions.py:36: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.
To accept the future behavior, pass 'sort=False'.
To retain the current behavior and silence the warning, pass 'sort=True'.
  actions = concat([actions, dividends]).sort_index(ascending=False)
              action  value
2018-12-06  DIVIDEND   0.70
2018-06-06  DIVIDEND   2.76
>>>

**Comment by bashtage** [comment]
Probably a data provider issue.
