### ISSUE TITLE
Difficulty pulling any kind of data. Please help.

### ISSUE THREAD

**Issue by ram367** [pydata/pandas-datareader#636]
**When I try to run this or anything with the data reader I am getting errors:**

import pandas_datareader.data as web

from datetime import datetime

f = web.DataReader('F', 'robinhood')

f.head()

**Here's the error output:**

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    f = web.DataReader('F', 'robinhood')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas_datareader/data.py", line 391, in DataReader
    session=session).read()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas_datareader/base.py", line 77, in read
    return self._read_one_data(self.url, self.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas_datareader/base.py", line 86, in _read_one_data
    out = self._get_response(url, params=params).json()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas_datareader/base.py", line 136, in _get_response
    last_response_text = response.text.encode(response.encoding)
TypeError: encode() argument 1 must be str, not None

I've tried retrieving data from many of the sources on the data_reader github page including Tiingo, Robinhood, and IEX, and they all return similar errors. I tried google and yahoo too, but I don't think those are supposed to work. If anyone knows what the issue is or has recommendations for market data sources that offer minute data I would greatly appreciate it.

Thank you!

**Comment by tanujsm** [comment]
The code mentioned below is working for fetching data of Bank of America(2006-16).
Moreover google is not working but yahoo worked for me.
you can try this code it's working and fetching data.
start=datetime.datetime(2006,1,1)
end=datetime.datetime(2016,1,1)
BAC = data.DataReader("BAC",'yahoo',start,end)

**Comment by bashtage** [comment]
Closing as answered.
