### ISSUE TITLE
ImmediateDeprecationError

### ISSUE THREAD

**Issue by bhanoo18** [pydata/pandas-datareader#654]
Traceback (most recent call last):

  File "<ipython-input-3-50fcb9e2a233>", line 13, in <module>
    panel_data = data.DataReader('INPX', 'google', start_date, end_date)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas_datareader\data.py", line 316, in DataReader
    session=session).read()

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas_datareader\google\daily.py", line 36, in __init__
    raise ImmediateDeprecationError(DEP_ERROR_MSG.format('Google finance'))

**Comment by saidv2007** [comment]
Yahoo Finance works,
try this instead:
panel_data=data.DataReader('INPX',start_date, end_date,data_source='yahoo')

**Comment by bashtage** [comment]
Closing as answered.
