### ISSUE TITLE
ImportError: cannot import name 'StringIO' from 'pandas.compat'

### ISSUE THREAD

**Issue by ranjitmishra** [pydata/pandas-datareader#675]
It can't be imported in Anaconda/Spyder IDE. It fails with 'import error on StringIO from pandas.compat'. I thought version 0.7.0 of datareader works woth pandas > 0.19. Isn't it? 

In [15]:import pandas_datareader.data as pdr
Traceback (most recent call last):

  File "<ipython-input-15-9559058eedd0>", line 1, in <module>
    import pandas_datareader.data as pdr

  File "C:\Users\cool\Anaconda3\lib\site-packages\pandas_datareader\__init__.py", line 2, in <module>
    from .data import (DataReader, Options, get_components_yahoo,

  File "C:\Users\cool\Anaconda3\lib\site-packages\pandas_datareader\data.py", line 7, in <module>
    from pandas_datareader.av.forex import AVForexReader

  File "C:\Users\cool\Anaconda3\lib\site-packages\pandas_datareader\av\__init__.py", line 3, in <module>
    from pandas_datareader.base import _BaseReader

  File "C:\Users\cool\Anaconda3\lib\site-packages\pandas_datareader\base.py", line 11, in <module>
    from pandas.compat import StringIO, bytes_to_str

ImportError: cannot import name 'StringIO' from 'pandas.compat' (C:\Users\cool\Anaconda3\lib\site-packages\pandas\compat\__init__.py)

**Comment by bashtage** [comment]
pip install pandas-datareader  --upgrade

**Comment by ranjitmishra** [comment]
Thanks a lot. I am facing another problem now. Will open a new issue.
