### ISSUE TITLE
ImportError: parent 'pandas_datareader' not in sys.modules

### ISSUE THREAD

**Issue by ranjitmishra** [pydata/pandas-datareader#676]
I upgraded pandas-datareader 0.7.0 to pandas-datareader 0.7.4 because 0.7.0 was failing with StringIO error. the upgraded one is also not working. the error is as below... pls help fix this...

In [16]: import pandas_datareader.data as pdr
[autoreload of pandas_datareader._version failed: Traceback (most recent call last):
  File "C:\Users\cool\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\cool\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 434, in superreload
    module = reload(module)
  File "C:\Users\cool\Anaconda3\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\cool\Anaconda3\lib\importlib\__init__.py", line 160, in reload
    name=parent_name) from None
ImportError: parent 'pandas_datareader' not in sys.modules
]

**Comment by bashtage** [comment]
Don't use autoreload.

**Comment by bashtage** [comment]
This is not a PDR issue. If you continue having problems, run pip uninstall pandas-datareader 2 or 3 times and then reinstall.
