### ISSUE TITLE
URGENT Issue with pulling certain Fama-French Data (Ken French’s Data Library): ValueError: Unknown string format

### ISSUE THREAD

**Issue by christianjauregui** [pydata/pandas-datareader#751]
The following fails despite 'F-F_momentum_factor' being a valid dataset string: 

>>> import pandas_datareader.data as web
>>> dfkf_dict = web.DataReader('F-F_Momentum_Factor', 'famafrench')
Traceback (most recent call last):
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 1861, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data)
  File "pandas/_libs/tslibs/conversion.pyx", line 200, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas_datareader/data.py", line 471, in DataReader
    session=session,
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas_datareader/famafrench.py", line 75, in read
    return super(FamaFrenchReader, self).read()
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas_datareader/base.py", line 100, in read
    return self._read_one_data(self.url, self.params)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas_datareader/famafrench.py", line 114, in _read_one_data
    df = read_csv(StringIO("Date" + src[start:]), **params)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 2069, in read
    index, names = self._make_index(data, alldata, names)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1542, in _make_index
    index = self._agg_index(index)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1621, in _agg_index
    arr = self._date_conv(arr)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 3190, in converter
    return generic_parser(date_parser, *date_cols)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/io/date_converters.py", line 40, in generic_parser
    results[i] = parse_func(*args)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas_datareader/famafrench.py", line 38, in _parse_date_famafrench
    return to_datetime(x)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 611, in to_datetime
    result = convert_listlike(np.array([arg]), box, format)[0]
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 302, in _convert_listlike_datetimes
    allow_object=True)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 1866, in objects_to_datetime64ns
    raise e
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 1857, in objects_to_datetime64ns
    require_iso8601=require_iso8601
  File "pandas/_libs/tslib.pyx", line 460, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 685, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 809, in pandas._libs.tslib.array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 803, in pandas._libs.tslib.array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 99, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/dateutil/parser.py", line 1161, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/chris.jauregui/anaconda3/lib/python3.7/site-packages/dateutil/parser.py", line 552, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format

However, the daily version results in no error:
>>> dfkf_dict = web.DataReader('F-F_Momentum_Factor_daily', 'famafrench')

WHAT IS THE ISSUE HERE? I recall not having this issue nearly a month ago...

**Comment by bashtage** [comment]
Works now.
