### ISSUE TITLE
Python 3.8 pandas-datareader ImportError

### ISSUE THREAD

**Issue by Marcodipi** [pydata/pandas-datareader#770]
Good evening,
I seem to be encountering issues when running pandas_datareader as per code shown here below:

import numpy as np
import pandas as pd
import pandas_datareader.data as web

Traceback (most recent call last):
  File "c:/Users/marco/AppData/Local/Programs/Python/Python38-32/Portfolio theory.py", line 6, in <module>
    import pandas_datareader.data as web
  File "C:\Users\marco\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas_datareader\__init__.py", line 2, in <module>     
    from .data import (
  File "C:\Users\marco\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas_datareader\data.py", line 11, in <module>        
    from pandas_datareader.av.forex import AVForexReader
  File "C:\Users\marco\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas_datareader\av\__init__.py", line 5, in <module>  
    from pandas_datareader._utils import RemoteDataError
  File "C:\Users\marco\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas_datareader\_utils.py", line 6, in <module>       
    from pandas_datareader.compat import is_number
ImportError: cannot import name 'is_number' from 'pandas_datareader.compat' (C:\Users\marco\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas_datareader\compat\__init__.py)

pandas and pandas-datareader versions are the latest ones available.

Thanks in advance for your help

**Comment by bashtage** [comment]
Fixed in master.
