### ISSUE TITLE
Fail to download data from yahoo on 01/13/2023

### ISSUE THREAD

**Issue by yuzhipeter** [pydata/pandas-datareader#958]
Hello, 

Data download fails from yahoo finance.  The error msg is 

df = web.DataReader("SPY", data_source='yahoo', start='2020-01-01', end='2020-03-03', session = sesh)
Traceback (most recent call last):

  File "C:\Users\peter\AppData\Local\Temp/ipykernel_25324/3322276019.py", line 1, in <module>
    df = web.DataReader("SPY", data_source='yahoo', start='2020-01-01', end='2020-03-03', session = sesh)

  File "C:\Users\peter\anaconda3\lib\site-packages\pandas\util\_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\peter\anaconda3\lib\site-packages\pandas_datareader\data.py", line 370, in DataReader
    return YahooDailyReader(

  File "C:\Users\peter\anaconda3\lib\site-packages\pandas_datareader\base.py", line 253, in read
    df = self._read_one_data(self.url, params=self._get_params(self.symbols))

  File "C:\Users\peter\anaconda3\lib\site-packages\pandas_datareader\yahoo\daily.py", line 231, in _read_one_data
    data = new_j['HistoricalPriceStore']

UnboundLocalError: local variable 'new_j' referenced before assignment

It was good yesterday, 01/12/2023. Thanks!

**Comment by devmsft-github** [comment]
Assume you installed pandas-datareader using this command
`pip install git+https://github.com/raphi6/pandas-datareader.git@ea66d6b981554f9d0262038aef2106dda7138316
`

Faced the same issue today, but based on [this commit](https://github.com/pydata/pandas-datareader/compare/main...raphi6:pandas-datareader:Yahoo!_Issue%23952), overwrote these 3 files:

folder = `/path/to/env/env-name/Lib/site-packages`

```
1) pandas_datareader/tests/io/test_jsdmx.py
2) pandas_datareader/tests/yahoo/test_options.py
3) pandas_datareader/yahoo/daily.py
```
Working as expected, waiting for Issue #952 merge to main branch and a release soon.

**Comment by yuzhipeter** [comment]
It works now. Thanks!

**Comment by devmsft-github** [comment]
1) Saved the 3 original files that came with the `pip install` to `[filename]_orig.py`
2) from [this commit](https://github.com/pydata/pandas-datareader/compare/main...raphi6:pandas-datareader:Yahoo!_Issue%23952), copied the content of the newest version of file_1
3) Opened `[file_1].py` under `/path/to/env/Lib/site-packages` and pasted content from (2) 
4) Repeat for `file_2` & `file_3`

**Comment by yuzhipeter** [comment]
The new files are broken again with yahoo finance

df = web.DataReader("SPY", data_source='yahoo', start='2023-01-01', end='2023-01-13', session = sesh)

Error msg

Traceback (most recent call last):

File "C:\Users\peter\AppData\Local\Temp/ipykernel_27516/630144412.py", line 1, in
df = web.DataReader("SPY", data_source='yahoo', start='2023-01-01', end='2023-01-13', session = sesh)

File "C:\Users\peter\anaconda3\lib\site-packages\pandas\util_decorators.py", line 207, in wrapper
return func(*args, **kwargs)

File "C:\Users\peter\anaconda3\lib\site-packages\pandas_datareader\data.py", line 370, in DataReader
return YahooDailyReader(

File "C:\Users\peter\anaconda3\lib\site-packages\pandas_datareader\base.py", line 253, in read
df = self._read_one_data(self.url, params=self._get_params(self.symbols))

File "C:\Users\peter\anaconda3\lib\site-packages\pandas_datareader\yahoo\daily.py", line 227, in _read_one_data
new_j = decrypt_cryptojs_aes(

File "C:\Users\peter\anaconda3\lib\site-packages\pandas_datareader\yahoo\daily.py", line 81, in decrypt_cryptojs_aes
plaintext = unpad(plaintext, 16, style="pkcs7")

File "C:\Users\peter\anaconda3\lib\site-packages\Crypto\Util\Padding.py", line 92, in unpad
raise ValueError("Padding is incorrect.")

ValueError: Padding is incorrect.

Thanks!

**Comment by devmsft-github** [comment]
This time went the route of  `yfinance` as below

```
import yfinance as yf
yf.pdr_override()
```

then

`data = yf.download(ticker, start=start_date, end=end_date, threads=False)     # or threads=True`

This works with raphi6's pandas-datareader fixes I suggested above, so all you need is `yfinance`.

**Comment by fouad09** [comment]
This still not working !!!

**Comment by suaide** [comment]
No update on this issue? Is pandas-datareader abandoned?

**Comment by devmsft-github** [comment]
`pandas-datareader` works as expected with the `yfinance` fix [above](https://github.com/pydata/pandas-datareader/issues/958#issuecomment-1407735807).

What is not working?

**Comment by Luminilion** [comment]
Hey there, 
The `yfinance` module offers an override of the yahoo finance from datareader.
It only requires to add one line.

```
from pandas_datareader import data as pdr

import yfinance as yf
yf.pdr_override() # <== that's all it takes :-)

# download dataframe
data = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2017-04-30")
```

You can check the comment on the official `yfinance` repo -> [here](https://github.com/ranaroussi/yfinance#pandas_datareader-override)

Hope it helps, it worked for me.
