### ISSUE TITLE
Unable to fetch stock data from yahoo!

### ISSUE THREAD

**Issue by vikassnwl** [pydata/pandas-datareader#995]
Run the following code to reproduce the issue:
```python
import pandas_datareader as web
web.DataReader("AAPL", "yahoo", "1/1/2018", "1/1/2019")
```

You will get the following exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vikas/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 210, in wrapper
    return func(*args, **kwargs)
  File "/home/vikas/.local/lib/python3.8/site-packages/pandas_datareader/data.py", line 370, in DataReader
    return YahooDailyReader(
  File "/home/vikas/.local/lib/python3.8/site-packages/pandas_datareader/base.py", line 253, in read
    df = self._read_one_data(self.url, params=self._get_params(self.symbols))
  File "/home/vikas/.local/lib/python3.8/site-packages/pandas_datareader/yahoo/daily.py", line 152, in _read_one_data
    j = json.loads(re.search(ptrn, resp.text, re.DOTALL).group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Quelconque** [comment]
Problem seem to be caused by this code snippet (at line 149 in yahoo/daily.py):
       try:
            j = json.loads(re.search(ptrn, resp.text, re.DOTALL).group(1))
            data = j["context"]["dispatcher"]["stores"]["HistoricalPriceStore"]
        except KeyError as exc:
            msg = "No data fetched for symbol {} using {}"
            raise RemoteDataError(msg.format(symbol, self.__class__.__name__)) from exc


if pattern is not found, re.search() returns None while the programmer was expecting a KeyError exception.

Nobody fixed the problem in the last 8 months.
Is there still a pilot on this plane?

**Comment by sugizo** [comment]
**code**
```
import pandas_datareader.data as web
st = dt.datetime(2024, 1, 11)
en = dt.datetime(2024, 1, 19)
data = web.get_data_yahoo('AAPL', start = st, end = en)
print(data)
```

**result**
```
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-983731377189>](https://localhost:8080/#) in <cell line: 0>()
----> 1 data = web.get_data_yahoo('AAPL', start = st, end = en)
      2 print(data)

2 frames
[/usr/local/lib/python3.11/dist-packages/pandas_datareader/yahoo/daily.py](https://localhost:8080/#) in _read_one_data(self, url, params)
    150         ptrn = r"root\.App\.main = (.*?);\n}\(this\)\);"
    151         try:
--> 152             j = json.loads(re.search(ptrn, resp.text, re.DOTALL).group(1))
    153             data = j["context"]["dispatcher"]["stores"]["HistoricalPriceStore"]
    154         except KeyError:

AttributeError: 'NoneType' object has no attribute 'group'
```

best regards

**Comment by parinayrana** [comment]
It seems the data pattern on the Yahoo Finance site has changed, and the code in the `pandas_datareader` library is still based on the older pattern.

So I tried using the yfinance library instead, and it worked:

```python
import yfinance as yf
import datetime as dt

start = dt.datetime(2000, 1, 1)
end = dt.datetime(2024, 12, 31)

# Download historical data
df = yf.download("TSLA", start, end)

print(df.head())
